/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Signer,
  utils,
  BigNumberish,
  Contract,
  ContractFactory,
  Overrides,
} from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { Campaign, CampaignInterface } from "../Campaign";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_campaignGoal",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_campaignDeadline",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_creator",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "campaignDeadline",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "campaignGoal",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "creator",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50604051610310380380610310833981810160405281019061003291906100b2565b806000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff160217905550826001819055508160028190555050505061016b565b6000815190506100978161013d565b92915050565b6000815190506100ac81610154565b92915050565b6000806000606084860312156100c757600080fd5b60006100d58682870161009d565b93505060206100e68682870161009d565b92505060406100f786828701610088565b9150509250925092565b600061010c82610113565b9050919050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b6000819050919050565b61014681610101565b811461015157600080fd5b50565b61015d81610133565b811461016857600080fd5b50565b6101968061017a6000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c806302d05d3f146100465780631d6f822314610064578063ef068a7f14610082575b600080fd5b61004e6100a0565b60405161005b91906100ee565b60405180910390f35b61006c6100c4565b6040516100799190610109565b60405180910390f35b61008a6100ca565b6040516100979190610109565b60405180910390f35b60008054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b60025481565b60015481565b6100d981610124565b82525050565b6100e881610156565b82525050565b600060208201905061010360008301846100d0565b92915050565b600060208201905061011e60008301846100df565b92915050565b600061012f82610136565b9050919050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b600081905091905056fea2646970667358221220d6c6c27244d9d855e29fe2f535fe3d88d9f6fd2b60525cc26a84e1b9328494c564736f6c63430008040033";

export class Campaign__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    _campaignGoal: BigNumberish,
    _campaignDeadline: BigNumberish,
    _creator: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Campaign> {
    return super.deploy(
      _campaignGoal,
      _campaignDeadline,
      _creator,
      overrides || {}
    ) as Promise<Campaign>;
  }
  getDeployTransaction(
    _campaignGoal: BigNumberish,
    _campaignDeadline: BigNumberish,
    _creator: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(
      _campaignGoal,
      _campaignDeadline,
      _creator,
      overrides || {}
    );
  }
  attach(address: string): Campaign {
    return super.attach(address) as Campaign;
  }
  connect(signer: Signer): Campaign__factory {
    return super.connect(signer) as Campaign__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): CampaignInterface {
    return new utils.Interface(_abi) as CampaignInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Campaign {
    return new Contract(address, _abi, signerOrProvider) as Campaign;
  }
}
