/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface CampaignInterface extends ethers.utils.Interface {
  functions: {
    "campaignDeadline()": FunctionFragment;
    "campaignGoal()": FunctionFragment;
    "creator()": FunctionFragment;
    "isSuccessful()": FunctionFragment;
    "pledge()": FunctionFragment;
    "pledges(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "campaignDeadline",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "campaignGoal",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "creator", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isSuccessful",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pledge", values?: undefined): string;
  encodeFunctionData(functionFragment: "pledges", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "campaignDeadline",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "campaignGoal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "creator", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isSuccessful",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pledge", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pledges", data: BytesLike): Result;

  events: {};
}

export class Campaign extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: CampaignInterface;

  functions: {
    campaignDeadline(overrides?: CallOverrides): Promise<[BigNumber]>;

    campaignGoal(overrides?: CallOverrides): Promise<[BigNumber]>;

    creator(overrides?: CallOverrides): Promise<[string]>;

    isSuccessful(overrides?: CallOverrides): Promise<[boolean]>;

    pledge(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    pledges(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  campaignDeadline(overrides?: CallOverrides): Promise<BigNumber>;

  campaignGoal(overrides?: CallOverrides): Promise<BigNumber>;

  creator(overrides?: CallOverrides): Promise<string>;

  isSuccessful(overrides?: CallOverrides): Promise<boolean>;

  pledge(
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  pledges(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    campaignDeadline(overrides?: CallOverrides): Promise<BigNumber>;

    campaignGoal(overrides?: CallOverrides): Promise<BigNumber>;

    creator(overrides?: CallOverrides): Promise<string>;

    isSuccessful(overrides?: CallOverrides): Promise<boolean>;

    pledge(overrides?: CallOverrides): Promise<void>;

    pledges(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    campaignDeadline(overrides?: CallOverrides): Promise<BigNumber>;

    campaignGoal(overrides?: CallOverrides): Promise<BigNumber>;

    creator(overrides?: CallOverrides): Promise<BigNumber>;

    isSuccessful(overrides?: CallOverrides): Promise<BigNumber>;

    pledge(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    pledges(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    campaignDeadline(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    campaignGoal(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    creator(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isSuccessful(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pledge(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    pledges(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
